name: AntiMove
author: Ondrej
version: 1.0
main: me.Ondrej.AntiMove.Main
description: Antimove plugin
commands:
 freeze:
  description: Freeze command
 unfreeze:
  description: Unfreeze command
permissions:
 antimove.freeze:
  default: op
 antimove.unfreeze:
  default: op